# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anand Sai Mishra
title: Cloud Engineer
email: anandsai.mishra@gmail.com
website: www.github.com/anandsaimishra

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: AnandSMishra
github_username:  anandsaimishra
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: anandsaimishra
linkedin_username: anandsaimishra
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an upcoming Computer Science professional with a master’s degree from CSU Dominguez Hills. 
  I have gained working experience in software development, Project Management and Customer Facing experience from my 
  academic and working experience. I am strong, confident, adaptable and have plenty of theoretical and practical 
  experience in the field with a strong desire to prove my credential and values given a chance. 

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: California State University - Dominguez Hills, Carson, California
        caption: 2018 - 2020
        sub_title: Master's of Science, Computer Science
        quote: >
          Specializing in Distributed Systems and Networking.
        description: | # this will include new lines to allow paragraphs
          During my time at CSU Dominguez Hills I spent my time learning Cloud Computing on AWS, Azure and GCP. I have also worked on many academic projects with my professors.
          I have worked on projects including <mark>Data Center Optimization</mark>, <mark>Homomorphic Cryptography</mark>, <mark>Energy Optimized Algorithms on Cluster Formation</mark>.
          I have also worked on IOS development and Real time Object detection using <mark>Yolov3</mark>, Sentiment Analysis and Emotion Detection using <mark>PyTorch</mark>, <mark>BERT</mark>, <mark>TensorFlow</mark>.
      - layout: left
        title: National Institute of Technology, Rourkela, INDIA
        caption: 2013 - 2018
        sub_title: Bachelor's of Technology, Computer Science & Engineering
        #quote: >
          #Specializing in Distributed Systems and Networking.
        description: | # this will include new lines to allow paragraphs
          While working on my Bachelor's of Technology I focused on learning the concepts of Database management in <mark>Oracle 12c</mark> and <mark>MySQL</mark>
          I also worked on <mark>Cryptography</mark> and <mark>IOT</mark>. I worked towards developing my basic skills in Computer Science which would help in making a career in Computer Scinece.


  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: California State University - Dominguez Hills
        link: https://www.csudh.edu/csc
        # link_text: boringcompany.com
        sub_title: Adjunct  Part-Time Lecturer.
        caption: September 2019 - Present
        quote: >
          Teaching subjects like CTC-228 (Computer Networks and Operating System), CTC-328 (Computer Forensics) and ITC-395 (IOS Development and Programming)
        description: | # this will include new lines to allow paragraphs
                  Developed courses that involved subjects like Operating Systems and Networks (CTC228), Computer Forensics and Investigation (CTC328) & Advanced Database Management Systems (CSC553) which covered topics like virtualization, file management systems, Process handling, networking layers network security, Database Management, Data Analytics and Optimization usage of Artificial Intelligence in security and modern data center optimization.
      - layout: left
        title: CodePath*Org 
        link: https://www.codepath.org/
        # link_text: boringcompany.com
        sub_title: IOS Development TechFellow
        caption: May 2020 - Present
        quote: >
          Working in collaboration with CodePath and CSU Dominguez Hills to develop and establish the IOS Programming course at CSU Dominguez Hills.
        description: | # this will include new lines to allow paragraphs
            Designed multiple IOS applications that included Twitter Client application, Movie review Application and Resturant Review Application, Also helped design a COVID Screening application that gives the user determine if he/she needs to isolate themselves based on the self reported conditions.
      - layout: left
        title: California State University Dominguez Hills
        link: www.csudh.edu/iss
        # link_text: boringcompany.com
        sub_title: Graduate Student Assistant
        caption: February 2020 - August 2020
        quote: >
          Worked as a student assistant at International Student Services and helped develop the next generation Database for holding student information.
        description: | # this will include new lines to allow paragraphs

            
  - title: Projects and Academic Experiance # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Handwriting Recognition for numbers in Roman Script
        link: https://github.com/anandsaimishra/Handwriting-Recognition
        link_text: Github Link
        additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
           # url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Created the project as a way to learn <mark> TensorFlow </mark>, <mark>Keras</mark> and <mark>GitHub</mark>
        description: | # this will include new lines to allow paragraphs
          Developed an ML and Artificial Neural Network powered handwriting detection system using TensorFlow Framework and Keras Backend to enable handwriting recognition with 99% accuracy.
      
      - layout: left
        title: IMDB - Movie Review sentiment analyser
        link: https://github.com/anandsaimishra/Basic-Sentiment-Analyzer
        link_text:  Github Link
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Created the project as a way to learn <mark> PyTorch </mark>, <mark>Pandas</mark> and <mark>TensorFlow</mark>
        description: | # this will include new lines to allow paragraphs
          Developed a TensorFlow and Keras(Backend) powered sentiment analyzer that can detect if the review left for a particular movie is good or bad based on the terms used in the Review. It uses Word Embedding for the mapping.
      
      - layout: left
        title: Real-Time Object Detection using YOLO v3
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Created the project as a way to learn <mark> YOLOv3 </mark>, <mark>Object Detection</mark> and <mark>Machine Learning</mark>
        description: | # this will include new lines to allow paragraphs
          Developed an ML and Artificial Neural Network powered handwriting detection system using TensorFlow Framework and Keras Backend to enable handwriting recognition with 99% accuracy.

      - layout: left
        title: Asynchronous Cryptography based Inter-Vehicular Ad-Hoc Message Authentication
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Created the project as a way to learn <mark> Cryptography </mark>, <mark>Message Authentication</mark> and <mark>Ad-Hoc Networks</mark>
        description: | # this will include new lines to allow paragraphs
          Worked on a research project based on using asynchronous methods to authenticate messages being passed between various vehicles and posts appointed at the roads for guidence and updates.
      - layout: left
        title: Lwitter - Twitter Client using Twitter API (IOS Application)
        link: https://github.com/anandsaimishra/TwitterClient---No-Ads
        link_text:  Github Link
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Created the project as a way to learn <mark> IOS Development </mark>,<mark> XCODE </mark>, <mark>AlamoFire</mark> ,<mark>RestFUL API</mark> and <mark>SWIFT 5</mark>
        description: | # this will include new lines to allow paragraphs
          Built on Xcode 12, AlamoFire and Twitter Official API to build a twitter Client that can serve as the main twitter client for users.
      
      - layout: left
        title: Improving Sentiment Analysis by Introducing Emotion Detection 
        #link: https://github.com/anandsaimishra/Basic-Sentiment-Analyzer
        #link_text:  Github Link
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Project developed for the compleation of my Master's project using <mark>PyTorch</mark>, <mark> BERT </mark> and <mark> Multiple Classifiers </mark>
        description: | # this will include new lines to allow paragraphs
          Developed a TensorFlow and Keras(Backend) powered sentiment analyzer that can detect if the review left for a particular movie is good or bad based on the terms used in the Review. It uses Word Embedding for the mapping.
      


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Cloud Computing, Computer networks, Cryptography and software engineering some of my other interests and hobbies are:
      - Playing Chess
      - Photography - http://instagram.com/anandsaimishra
      - Computer Gaming - FIFA 21, Call Of Duty - MW 2
      - Computer Harware Assembly

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
